### PR TITLE
Fix S12 report for tasks without TpPro

### PR DESCRIPTION
**Pull request by sim6**

### CODE REVIEW

**Comment by ecarreras** [comment]
Remember to check if primestg library is also affected

**Comment by sim6** [comment]
@ecarreras primestg is affected too gisce/primestg#9

**Comment by sim6** [comment]
@tinogis done via d6f269515f1cd367f450afee5aef5ea82e8f8fd5

**Comment by sim6** [comment]
:)

**Comment by sim6** [comment]
@ecarreras Done https://pypi.python.org/pypi/switching/2.6.24

**Pull request merged**
